#!/bin/bash
#
# squeezesync
#	-- watch a local itunes installation for changes and sync them to a 
#	   remote squeezeboxserver using rsync.
#
# author: <greg@automagick.us>
#
# Requires: ssh, rsync, curl
#
# Copyright 2010 Greg Boyington.  All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without modification, are
# permitted provided that the following conditions are met:
# 
#    1. Redistributions of source code must retain the above copyright notice, this list of
#       conditions and the following disclaimer.
# 
#    2. Redistributions in binary form must reproduce the above copyright notice, this list
#       of conditions and the following disclaimer in the documentation and/or other materials
#       provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY GREG BOYINGTON ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# The views and conclusions contained in the software and documentation are those of the
# authors and should not be interpreted as representing official policies, either expressed
# or implied, of Greg Boyington.
#

#### LOCAL ITUNES CONFIGURATION ####

USER=greg
ITUNES_DIR=/Users/${USER}/Music/iTunes
MUSIC_DIR=${ITUNES_DIR}/iTunes\ Music
ITUNES_XML=${ITUNES_DIR}/iTunes\ Music\ Library.xml


#### REMOTE SQUEEZEBOXSERVER CONFIGURATION ####

# Note: configure SSH to allow a login by this user without a password.
REMOTE_USER=greg
REMOTE_HOST=garrett

# where should the tracks be synced to?
REMOTE_MUSIC=/usr/local/music/music

# where should the iTunes Library XML file be synced to?
REMOTE_LIBRARY=/usr/local/music/itunesdb

# the URL for the squeezeboxserver (needed to force a rescan)
SQZBOX_URL=http://garrett:9000

# How long the script should wait before checking for changes, in seconds.
SLEEP_INTERVAL=30


#### MAIN LOOP (THE WORKIN' OVERTIME PART) ####

cd "${MUSIC_DIR}"
while true; do 

	# Create a string representing the state of the iTunes library. 
	# We do this by tracking total disk usage and a checksum of the
	# directory listing.  This ensures we notice any change to the
	# directory structure, even ones (like renames) that don't change
	# total disk usage, as well as solving a race condition for files
	# being modified while the sync runs.  Finally, we checksum the
	# iTunes XML file to detect changes to playlists and other metadata.
	#
	i="`du |tail -1|cut -f1` `find . |cksum` `cksum \"${ITUNES_XML}\"|cut -f1 -d\ `" 

	# Compare the current state of the iTunes library ($i) to the previous state ($j).
	if [[ $i != $j ]]; then 

		# changes were detected, so use rsync to update the squeezebox library
		rsync -av --delete "${MUSIC_DIR}/" "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_MUSIC}"

		# copy the iTunes Music Library.xml file so playlists and such are preserved.
		rsync -qav "${ITUNES_XML}" "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_LIBRARY}"

		# request a rescan of the squeezecenter library
		curl -so /dev/null "${SQZBOX_URL}/status.html?p0=rescan"
	fi

	# remember the current state of the library for the next check, and wait 30 seconds.
	j="$i"
	sleep ${SLEEP_INTERVAL}
done
